; Position Format: Key#KeyCount, by default using 7K if not specified key not defined
; Value Format: X, Y, AnchorPointX?, AnchorPointY?, TintColor?
; AnchorPoint values range between 0 to 1, and set to 0 by default
; TintColor are RGB 255:255:255 which set to RGB 255:255:255 (white) by default (unused)

[Key#7]
ImageFlip = 0|0|0|0|0|0|0
ColumnStart = 306
;ColumnWidth = 28,22,28,32,28,22,28
;KeyOffset = 12
KeyButton = 306,486|337,487|346,486|376,486|415,486|447,487|456,486
KeyButton0 = blank
KeyButton1 = blank
KeyButton2 = blank
KeyButton3 = blank
KeyButton4 = blank
KeyButton5 = blank
KeyButton6 = blank
KeyDown0 = Key0Down
KeyDown1 = Key1Down
KeyDown2 = Key2Down
KeyDown3 = KeySDown
KeyDown4 = Key4Down
KeyDown5 = Key5Down
KeyDown6 = Key6Down

[Key#6]
KeyButton = 306,486|336,486|366,486|396,486|426,486|456,486

[Key#5]
KeyButton = 306,486|344,486|381,486|419,486|456,486

[Key#4]
KeyButton = 306,486|356,486|406,486|456,486

[Numerics]
; Numerics format
; Value format: X, Y, MaxDigits?, Direction?, FillWithZero?
; MaxDigis default is 0, Direction default is RIGHT, and FillWithZero is false
Score = 794,18,99,LEFT,FALSE
Jam = 400,120,99,MID,FALSE
Combo = 400,200,99,MID,FALSE
LongNoteCombo = 400,300,99,MID,FALSE
Stats = 794,95,99,LEFT,false|794,128,99,LEFT,false|794,161,99,LEFT,false|794,194,99,LEFT,false|794,62,99,LEFT,false
Minute = 999,999,99,LEFT,FALSE
Second = 999,999,2,LEFT,TRUE

[Sprites]
; Value format: NumOfFrames, X, Y, AnchorPointX?, AnchorPointY?
; NumOfFrames = How much your image Sprite, put the correct number
; Same with position
JamLogo = 400,100,0.5,0.5,15.0
LifeBar = 506,272
ComboLogo = 400,200,0.5,0.8,13.33
LongNoteLogo = 400,290,0.5,0.5,60.0
TargetBar = 306,408,0,0,5.0

[Effects]
; Value format: X, Y, FPS?, TintColor?
; By default, the effects is hardcoded to the game
; Using X, Y can add offset to the game specified position
HitEffect = 0,10
HoldEffect = 0,10

[UI]
Exit = 7,5,75,59
Title = 45,6,250,40
Judge = 400,360,0.5,0.5
JamGauge = 333,547
Pill = 286,468|286,419|286,370|286,321|286,272
WaveGage = 311,535
ExitButton = 754,576
PlayingBG = 0,0
Playfield = 0,0
PlayFooter = 0,0
BPM = 190,585
NoteMods = 7,28
VisualMods = 7,66