[Notes#7]
; NumOfFrames,fileName
; NOTE: fileName will assign the index (for ex: fileName0.png) automaticly
; Only PNG is supported

LaneHit0 = 1,1-,30.0
LaneHold0 = 1,1hold-,30.0

LaneHit1 = 1,2-,30.0
LaneHold1 = 1,2hold-,30.0

LaneHit2 = 1,1-,30.0
LaneHold2 = 1,1hold-,30.0

LaneHit3 = 1,3-,30.0
LaneHold3 = 1,3hold-,30.0

LaneHit4 = 1,1-,30.0
LaneHold4 = 1,1hold-,30.0

LaneHit5 = 1,2-,30.0
LaneHold5 = 1,2hold-,30.0

LaneHit6 = 1,1-,30.0
LaneHold6 = 1,1hold-,30.0

NoteTrailUp = 1,TrailUp
NoteTrailDown = 1,TrailDown