; Vec postfix = positions + size
; Text postifx = self explainitory
; Note: value 0 means it will use default value of ImGui auto placement, considering use 1

[MenuBar]
Title = "Unnamed O2 Game Clone"

[Buttons]


