
[Positions#7]
; Position Format: Positions#KeyCount, by default using 7K if not specified key not defined
; Value Format: X, Y, AnchorPointX?, AnchorPointY?, TintColor?
; AnchorPoint values range between 0 to 1, and set to 0 by default
; TintColor are RGB 255:255:255 which set to RGB 255:255:255 (white) by default (unused)
KeyButton = 23,486|51,485|65,486|91,485|134,486|161,485|175,486
KeyLighting = 23,0|51,0|73,0|101,0|133,0|161,0|183,0
JamGauge = 23,537
HealthBar = 800,60
Pill = 4,454|4,410|4,366|4,322|4,266
ExitButton = 760,542
WaveGage = 312,27
Playfield = 0,0
Title = 314,4
PlayFooter = 0,0

[Numerics]
; Numerics format
; Value format: X, Y, MaxDigits?, Direction?, FillWithZero?
; MaxDigis default is 0, Direction default is RIGHT, and FillWithZero is false
Score = 188,576,8,LEFT,FALSE
Jam = 116,120,4,MID,FALSE
LongNoteCombo = 117,300,5,MID,FALSE
Stats = 320,578,9,LEFT,FALSE|390,578,9,LEFT,FALSE|320,588,9,LEFT,FALSE|390,588,9,LEFT,FALSE|346,563,9,LEFT,FALSE
Minute = 347,569,9,LEFT,FALSE
Second = 409,569,2,LEFT,TRUE

[Sprites]
; Value format: NumOfFrames, X, Y, AnchorPointX?, AnchorPointY, FrameTime
; NumOfFrames = How much your image Sprite, put the correct number
; NOTE: fileName will assign the index (for ex: fileName0.png) automaticly
; Same with position
JamLogo = 8,116,97,0.5,0.5,13.33
LifeBar = 1,221,266,0,0,30.0
LongNoteLogo = 1,117,290,0.5,0.5,60.0
TargetBar = 2,23,408,0,0,5.0

[Rects]
Exit = 760,542,75,59
Title = 314,4,256,40