
[Positions#7]
; Position Format: Positions#KeyCount, by default using 7K if not specified key not defined
; Value Format: X, Y, AnchorPointX?, AnchorPointY?, TintColor?
; AnchorPoint values range between 0 to 1, and set to 0 by default
; TintColor are RGB 255:255:255 which set to RGB 255:255:255 (white) by default (unused)
KeyButton = 5,488|35,487|46,488|73,487|116,488|145,487|156,488
KeyLighting = 5,0|33,0|55,0|83,0|115,0|143,0|165,0
JamGauge = 5,539
HealthBar = 800,60
Pill = 203,146|203,111|203,76|203,41|203,6
ExitButton = 286,506
WaveGage = 200,525
Playfield = 0,0
PlayFooter = 0,0
Title = 205,544

[Numerics]
; Numerics format
; Value format: X, Y, MaxDigits?, Direction?, FillWithZero?
; MaxDigis default is 0, Direction default is RIGHT, and FillWithZero is false
Score = 785,15,99,LEFT,FALSE
Jam = 99,120,4,MID,FALSE
LongNoteCombo = 99,300,5,MID,FALSE
Stats = 99,576,99,LEFT,FALSE|169,576,99,LEFT,FALSE|99,586,99,LEFT,FALSE|169,586,99,LEFT,FALSE|114,562,99,LEFT,FALSE
Minute = 347,569,99,LEFT,FALSE
Second = 409,569,2,LEFT,TRUE

[Sprites]
; Value format: NumOfFrames, X, Y, AnchorPointX?, AnchorPointY, FrameTime
; NumOfFrames = How much your image Sprite, put the correct number
; NOTE: fileName will assign the index (for ex: fileName0.png) automaticly
; Same with position
JamLogo = 8,99,102,0.5,0.5,14.0
LifeBar = 12,203,187,0,0,15.0
LongNoteLogo = 1,99,290,0.5,0.5,60.0
TargetBar = 2,4,408,0,0,5.0

[Rects]
Exit = 200,506,140,40
Title = 205,544,191,40